<a href="https://colab.research.google.com/github/8zali9/DeepLearning-PyTorch/blob/main/courseNotebooks/pytorch_prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.2.1+cu121


In [3]:
scalar = torch.tensor(7)
scalar.ndim
scalar.item()
scalar.shape

torch.Size([])

In [4]:
vector = torch.tensor([1, 2])
vector.ndim
vector.shape

torch.Size([2])

In [5]:
MATRIX = torch.tensor([[1, 2], [3, 4], [4, 5]])
MATRIX

tensor([[1, 2],
        [3, 4],
        [4, 5]])

In [6]:
MATRIX.ndim
MATRIX[1]
MATRIX.shape

torch.Size([3, 2])

In [7]:
TENSOR = torch.tensor([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
TENSOR
TENSOR[1, 1]
TENSOR.ndim

2

In [8]:
randomTensor = torch.rand(1, 1, 2)
randomTensor.ndim, randomTensor.shape

(3, torch.Size([1, 1, 2]))

# Tensors with all 0s or 1s

In [9]:
zeros = torch.zeros(3, 4, 3)
zeros.ndim

3

In [10]:
ones = torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
tensor_with_ranges = torch.arange(1, 11)
tensor_with_ranges

tensor_arange_anotherMethod = torch.arange(start=1, end=11, step=2)
tensor_arange_anotherMethod

tensor([1, 3, 5, 7, 9])

In [12]:
tensor_range_zeros = torch.zeros_like(input=tensor_with_ranges)
tensor_range_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Data Types

In [13]:
tensor_32bit_int = torch.tensor([1, 2, 3], dtype=torch.int32)
tensor_32bit_int

tensor([1, 2, 3], dtype=torch.int32)

In [14]:
tensor_float_type = torch.tensor([0.1, 0.2, 0.3])
tensor_float_type.dtype

torch.float32

###**Issues that you can run into while dealing with tensors**

In [15]:
print(tensor_float_type.dtype)
print(tensor_float_type.shape)
print(tensor_float_type.device)

torch.float32
torch.Size([3])
cpu


### Tensor Operations

In [16]:
tempTensor = torch.tensor([1, 2, 3])

In [17]:
# first normal way to add: (same for subtraction)
tensorAdd1 = tempTensor + 10

# second way using a function: (same for subtraction)
tensorAdd2 = torch.add(tempTensor, 20)
tensorAdd1, tensorAdd2

(tensor([11, 12, 13]), tensor([21, 22, 23]))

In [18]:
multiplicationTensor1 = tempTensor * 2
multiplicationTensor2 = torch.mul(tempTensor, 3)
multiplicationTensor1, multiplicationTensor2

(tensor([2, 4, 6]), tensor([3, 6, 9]))

### **MATRIX MULTIPLICATION**

### Rules that are obvious:
* since the matrices of the order (R1, C1) & (R2, C2);
1. when multiplied, results in the matrix of order (R1, C2).
2. But can only be multiplied iff C1 == R2.

In [19]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
torch.matmul(t1, t2) # this is the dot product of these two tensors i.e. vector dot product

tensor(32)

In [20]:
# t1 an t2 cannot be multiplied. But if we manipulate either one of them, we can then mutiply
tensorFinal = torch.matmul(t1, t2.T)
tensorFinal

<ipython-input-20-ad433c162190>:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3637.)
  tensorFinal = torch.matmul(t1, t2.T)


tensor(32)

## Matrix mean, sum etc

In [21]:
x = torch.arange(start = 1, end = 50, step = 5)
x.dtype # currently it has a data type of int64 which is long. Mean function won't work for this datatype. We have to convert it into float32
print(torch.mean(x.type(torch.float32)))
# or another way to do that:
print(x)
print(x.type(torch.float32).mean())
print(x.min())
print(x.max())
print(x.sum())

# To find the position of the min / max val : use -> argmin / argmax -> returns the index of the min or max value
print(x.argmin())
print(x.argmax())

tensor(23.5000)
tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])
tensor(23.5000)
tensor(1)
tensor(46)
tensor(235)
tensor(0)
tensor(9)


# Reshaping a tensor


In [22]:
x1 = x.reshape(1, 10)
x2 = x.reshape(10, 1)
x3 = x.reshape(5, 2)
x4 = x.reshape(2, 5)
print(x, "\n")
print(x1, "\n")
print(x2, "\n")
print(x3, "\n")
print(x4, "\n")

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46]) 

tensor([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46]]) 

tensor([[ 1],
        [ 6],
        [11],
        [16],
        [21],
        [26],
        [31],
        [36],
        [41],
        [46]]) 

tensor([[ 1,  6],
        [11, 16],
        [21, 26],
        [31, 36],
        [41, 46]]) 

tensor([[ 1,  6, 11, 16, 21],
        [26, 31, 36, 41, 46]]) 



In [23]:
anotherView = x.view(10, 1)

anotherView, x

(tensor([[ 1],
         [ 6],
         [11],
         [16],
         [21],
         [26],
         [31],
         [36],
         [41],
         [46]]),
 tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46]))

### STACKING TENSORS

In [24]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
verticallyStackedTensors = torch.vstack((v1, v2))
horizontallyStackedTensors = torch.hstack((v1, v2))
print(verticallyStackedTensors)
print(horizontallyStackedTensors)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])


### SQUEEZING AND UNSQUEEZNG

In [25]:
to_squeeze_tensor = torch.rand(1, 10)

In [26]:
to_squeeze_tensor

squeezedTensor = to_squeeze_tensor.squeeze()
squeezedTensor

print(f"Before squeezing: {to_squeeze_tensor}\nAfter Squeezing: {squeezedTensor}")

Before squeezing: tensor([[0.0537, 0.0584, 0.3358, 0.1695, 0.7810, 0.9945, 0.7271, 0.2469, 0.5676,
         0.9473]])
After Squeezing: tensor([0.0537, 0.0584, 0.3358, 0.1695, 0.7810, 0.9945, 0.7271, 0.2469, 0.5676,
        0.9473])


In [27]:
to_unsqueeze_tensor = squeezedTensor
unsqueezedTensor0 = to_unsqueeze_tensor.unsqueeze(dim = 0)
unsqueezedTensor1 = to_unsqueeze_tensor.unsqueeze(dim = 1)

print(f"Before unsqueezing: {to_unsqueeze_tensor}\nAfter unsqueezing\nwith dim = 0: {unsqueezedTensor0}\nwith dim = 1: {unsqueezedTensor1}")

Before unsqueezing: tensor([0.0537, 0.0584, 0.3358, 0.1695, 0.7810, 0.9945, 0.7271, 0.2469, 0.5676,
        0.9473])
After unsqueezing
with dim = 0: tensor([[0.0537, 0.0584, 0.3358, 0.1695, 0.7810, 0.9945, 0.7271, 0.2469, 0.5676,
         0.9473]])
with dim = 1: tensor([[0.0537],
        [0.0584],
        [0.3358],
        [0.1695],
        [0.7810],
        [0.9945],
        [0.7271],
        [0.2469],
        [0.5676],
        [0.9473]])


### PERMUTE : changing the order or arrangement of a tensor

In [28]:
toBePermutedTensor = torch.rand(size = (1, 2, 2))
permutedTensor = toBePermutedTensor.permute(2, 1, 0)

print(f"Before permutting: \n{toBePermutedTensor}\n\nAfter permutting: \n{permutedTensor}")

Before permutting: 
tensor([[[0.0759, 0.1692],
         [0.8427, 0.2724]]])

After permutting: 
tensor([[[0.0759],
         [0.8427]],

        [[0.1692],
         [0.2724]]])


### Indexing

In [29]:
x = torch.arange(1, 11).reshape(5, 2)
x

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [30]:
print(x[:])         # to access the whole dim
print(x[:, 0])     # to access all elements from each row but from the 0th column
print(x[:, 1])      # to access all elements from each row but from the 1st column
print(x[0, 1])     # to access the element at 0th row, and the 1st column```

print(x[:])         # to access the whole dim
print(x[:, 0])     # to access all elements from each row but from the 0th column
print(x[:, 1])      # to access all elements from each row but from the 1st column
print(x[0, 1])     # to access the element at 0th row, and the 1st column

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])
tensor([1, 3, 5, 7, 9])
tensor([ 2,  4,  6,  8, 10])
tensor(2)
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])
tensor([1, 3, 5, 7, 9])
tensor([ 2,  4,  6,  8, 10])
tensor(2)


In [31]:
x3d = torch.arange(start = 8, end = 48, step = 4).reshape(1, 2, 5)
x3d[:, :] # to access all the elements
x3d[:, :, 0] # to access from every outer dimension (which is one in our case), and from each row, but access the 0th column value.

tensor([[ 8, 28]])

In [32]:
y = torch.arange(1, 10).reshape(1, 3, 3)
print(y)
y[:, 1, 1]
y[:, 1:, 1]
y[:, :, 2]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


tensor([[3, 6, 9]])

### numpy and pytorch

In [33]:
import numpy as np
import torch

x = np.array([1, 2, 3, 4, 5])
y = np.arange(1, 10)

# to convert a numpy array to a torch tensor ->
numpy2tensor = torch.from_numpy(x).type(torch.float32)
numpy2tensor.dtype
x.dtype

dtype('int64')

## random_seed -> Reproducibility

In [34]:
# random_seed -> in torch
seed = 42
torch.manual_seed(seed)
randomTensorExtra1 = torch.rand(1, 11)
torch.manual_seed(seed)
randomTensorExtra = torch.rand(1, 11)
print(randomTensorExtra, randomTensorExtra1)
print(randomTensorExtra == randomTensorExtra1)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
         0.1332, 0.9346]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
         0.1332, 0.9346]])
tensor([[True, True, True, True, True, True, True, True, True, True, True]])


In [35]:
# random_seed -> in numpy
np.random.seed(seed)
a = np.random.rand(1, 11)
np.random.seed(seed)
b = np.random.rand(1, 11)
print(a == b)

[[ True  True  True  True  True  True  True  True  True  True  True]]


Cheking if the GPU is available then using it, else default to CPU.

In [36]:
!nvidia-smi

Tue Apr  2 21:19:01 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [37]:
torch.cuda.is_available()

True

setting up device agnostic code (simply put -> if GPU is available, running then on it, else CPU)

In [38]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [39]:
anyTensor = torch.tensor([1, 2])
anyTensor.device # currently set to cpu

# to execute tensors on a gpu ->
anyTensor.to(device)

tensor([1, 2], device='cuda:0')

In [40]:
# numpy arrays do not support gpu, they can only be run on the cpu. to run numpy array, first change the device to the cpu
anyTensor.cpu().numpy()
anyTensor.device # cpu

device(type='cpu')