<a href="https://colab.research.google.com/github/8zali9/DeepLearning-PyTorch/blob/main/pytorch_prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
print(torch.__version__)

2.2.1+cu121


In [4]:
scalar = torch.tensor(7)
scalar.ndim
scalar.item()
scalar.shape

torch.Size([])

In [5]:
vector = torch.tensor([1, 2])
vector.ndim
vector.shape

torch.Size([2])

In [6]:
MATRIX = torch.tensor([[1, 2], [3, 4], [4, 5]])
MATRIX

tensor([[1, 2],
        [3, 4],
        [4, 5]])

In [7]:
MATRIX.ndim
MATRIX[1]
MATRIX.shape

torch.Size([3, 2])

In [8]:
TENSOR = torch.tensor([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
TENSOR
TENSOR[1, 1]
TENSOR.ndim

2

In [9]:
randomTensor = torch.rand(1, 1, 2)
randomTensor.ndim, randomTensor.shape

(3, torch.Size([1, 1, 2]))

# Tensors with all 0s or 1s

In [10]:
zeros = torch.zeros(3, 4, 3)
zeros.ndim

3

In [11]:
ones = torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
tensor_with_ranges = torch.arange(1, 11)
tensor_with_ranges

tensor_arange_anotherMethod = torch.arange(start=1, end=11, step=2)
tensor_arange_anotherMethod

tensor([1, 3, 5, 7, 9])

In [13]:
tensor_range_zeros = torch.zeros_like(input=tensor_with_ranges)
tensor_range_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Data Types

In [14]:
tensor_32bit_int = torch.tensor([1, 2, 3], dtype=torch.int32)
tensor_32bit_int

tensor([1, 2, 3], dtype=torch.int32)

In [15]:
tensor_float_type = torch.tensor([0.1, 0.2, 0.3])
tensor_float_type.dtype

torch.float32

###**Issues that you can run into while dealing with tensors**

In [16]:
print(tensor_float_type.dtype)
print(tensor_float_type.shape)
print(tensor_float_type.device)

torch.float32
torch.Size([3])
cpu


### Tensor Operations

In [17]:
tempTensor = torch.tensor([1, 2, 3])

In [18]:
# first normal way to add: (same for subtraction)
tensorAdd1 = tempTensor + 10

# second way using a function: (same for subtraction)
tensorAdd2 = torch.add(tempTensor, 20)
tensorAdd1, tensorAdd2

(tensor([11, 12, 13]), tensor([21, 22, 23]))

In [19]:
multiplicationTensor1 = tempTensor * 2
multiplicationTensor2 = torch.mul(tempTensor, 3)
multiplicationTensor1, multiplicationTensor2

(tensor([2, 4, 6]), tensor([3, 6, 9]))

### **MATRIX MULTIPLICATION**

### Rules that are obvious:
* since the matrices of the order (R1, C1) & (R2, C2);
1. when multiplied, results in the matrix of order (R1, C2).
2. But can only be multiplied iff C1 == R2.

In [20]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
torch.matmul(t1, t2) # this is the dot product of these two tensors i.e. vector dot product

tensor(32)

In [21]:
# t1 an t2 cannot be multiplied. But if we manipulate either one of them, we can then mutiply
tensorFinal = torch.matmul(t1, t2.T)
tensorFinal

<ipython-input-21-ad433c162190>:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3637.)
  tensorFinal = torch.matmul(t1, t2.T)


tensor(32)

## Matrix mean, sum etc

In [22]:
x = torch.arange(start = 1, end = 50, step = 5)
x.dtype # currently it has a data type of int64 which is long. Mean function won't work for this datatype. We have to convert it into float32
print(torch.mean(x.type(torch.float32)))
# or another way to do that:
print(x)
print(x.type(torch.float32).mean())
print(x.min())
print(x.max())
print(x.sum())

# To find the position of the min / max val : use -> argmin / argmax -> returns the index of the min or max value
print(x.argmin())
print(x.argmax())

tensor(23.5000)
tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])
tensor(23.5000)
tensor(1)
tensor(46)
tensor(235)
tensor(0)
tensor(9)


# Reshaping a tensor


In [23]:
x1 = x.reshape(1, 10)
x2 = x.reshape(10, 1)
x3 = x.reshape(5, 2)
x4 = x.reshape(2, 5)
print(x, "\n")
print(x1, "\n")
print(x2, "\n")
print(x3, "\n")
print(x4, "\n")

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46]) 

tensor([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46]]) 

tensor([[ 1],
        [ 6],
        [11],
        [16],
        [21],
        [26],
        [31],
        [36],
        [41],
        [46]]) 

tensor([[ 1,  6],
        [11, 16],
        [21, 26],
        [31, 36],
        [41, 46]]) 

tensor([[ 1,  6, 11, 16, 21],
        [26, 31, 36, 41, 46]]) 



In [24]:
anotherView = x.view(10, 1)

anotherView, x

(tensor([[ 1],
         [ 6],
         [11],
         [16],
         [21],
         [26],
         [31],
         [36],
         [41],
         [46]]),
 tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46]))

### STACKING TENSORS

In [25]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
verticallyStackedTensors = torch.vstack((v1, v2))
horizontallyStackedTensors = torch.hstack((v1, v2))
print(verticallyStackedTensors)
print(horizontallyStackedTensors)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])


### SQUEEZING AND UNSQUEEZNG

In [33]:
to_squeeze_tensor = torch.rand(1, 10)

In [34]:
to_squeeze_tensor

squeezedTensor = to_squeeze_tensor.squeeze()
squeezedTensor

print(f"Before squeezing: {to_squeeze_tensor}\nAfter Squeezing: {squeezedTensor}")

Before squeezing: tensor([[0.2106, 0.5942, 0.8224, 0.8444, 0.5206, 0.1093, 0.2005, 0.1773, 0.7163,
         0.3850]])
After Squeezing: tensor([0.2106, 0.5942, 0.8224, 0.8444, 0.5206, 0.1093, 0.2005, 0.1773, 0.7163,
        0.3850])


In [40]:
to_unsqueeze_tensor = squeezedTensor
unsqueezedTensor0 = to_unsqueeze_tensor.unsqueeze(dim = 0)
unsqueezedTensor1 = to_unsqueeze_tensor.unsqueeze(dim = 1)

print(f"Before unsqueezing: {to_unsqueeze_tensor}\nAfter unsqueezing\nwith dim = 0: {unsqueezedTensor0}\nwith dim = 1: {unsqueezedTensor1}")

Before unsqueezing: tensor([0.2106, 0.5942, 0.8224, 0.8444, 0.5206, 0.1093, 0.2005, 0.1773, 0.7163,
        0.3850])
After unsqueezing
with dim = 0: tensor([[0.2106, 0.5942, 0.8224, 0.8444, 0.5206, 0.1093, 0.2005, 0.1773, 0.7163,
         0.3850]])
with dim = 1: tensor([[0.2106],
        [0.5942],
        [0.8224],
        [0.8444],
        [0.5206],
        [0.1093],
        [0.2005],
        [0.1773],
        [0.7163],
        [0.3850]])


### PERMUTE : changing the order or arrangement of a tensor

In [50]:
toBePermutedTensor = torch.rand(size = (1, 2, 2))
permutedTensor = toBePermutedTensor.permute(2, 1, 0)

print(f"Before permutting: \n{toBePermutedTensor}\n\nAfter permutting: \n{permutedTensor}")

Before permutting: 
tensor([[[0.8408, 0.5304],
         [0.6020, 0.7969]]])

After permutting: 
tensor([[[0.8408],
         [0.6020]],

        [[0.5304],
         [0.7969]]])
