<a href="https://colab.research.google.com/github/8zali9/DeepLearning-PyTorch/blob/main/exercises/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###  PyTorch Fundamentals

In [2]:
import torch



2.   Create a random tensor with shape (7, 7).



In [3]:
randomTensor = torch.rand(7, 7)
print (randomTensor)

tensor([[0.4755, 0.2796, 0.0558, 0.3335, 0.8309, 0.7723, 0.0596],
        [0.8384, 0.7217, 0.9888, 0.5751, 0.5403, 0.5355, 0.9205],
        [0.4509, 0.1499, 0.8853, 0.4452, 0.5604, 0.8489, 0.7189],
        [0.8603, 0.6298, 0.0617, 0.1151, 0.7534, 0.2266, 0.5148],
        [0.8458, 0.0092, 0.0424, 0.4653, 0.5324, 0.6626, 0.9653],
        [0.4607, 0.9795, 0.8975, 0.2032, 0.7602, 0.1262, 0.0287],
        [0.5566, 0.2166, 0.0513, 0.3422, 0.7276, 0.9319, 0.8544]])


3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [4]:
x = torch.mul(randomTensor, 2)
anotherRandomTensor = torch.rand(1, 7)
print (f"Since the tensor's inner dimensions do not match. i.e. x shape:\n{x.shape}\n\nanotherRandomTensor:\n{anotherRandomTensor.shape}\n\nTherefore, anotherRandomTensor is transposed.")
matrixMultiplication = torch.matmul(x, anotherRandomTensor.T)
print(f"Multiplication of x and transposed anotherRandomTensor results in:\n{matrixMultiplication}")

Since the tensor's inner dimensions do not match. i.e. x shape:
torch.Size([7, 7])

anotherRandomTensor:
torch.Size([1, 7])

Therefore, anotherRandomTensor is transposed.
Multiplication of x and transposed anotherRandomTensor results in:
tensor([[1.8570],
        [4.0190],
        [3.3462],
        [2.2157],
        [3.1441],
        [1.9581],
        [3.3528]])


4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [5]:
# setting the variable seed
seed = 0
torch.manual_seed(seed)
anyTensor = torch.rand(7, 7)
torch.manual_seed(seed)
anyTensor2 = torch.rand(7, 7)
print(anyTensor == anyTensor2)

tensor([[True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True]])


5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234

In [6]:
# device agnostic code ->
device = "cuda" if torch.cuda.is_available() else "cpu"

seedForGpu = 1234
torch.cuda.manual_seed(seedForGpu)
torch.rand(1, 11).device

device(type='cpu')

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [12]:
seedExtra  = 1234
torch.manual_seed(seedExtra)
r1 = torch.rand(2, 3).to(device)
torch.manual_seed(seedExtra)
r2 = torch.rand(2, 3).to(device)
r1 == r2

tensor([[True, True, True],
        [True, True, True]], device='cuda:0')

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [14]:
tempR1intoR2 = matrixMultiplicationExtra = torch.matmul(r1, r2.T)
tempR1intoR2

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [16]:
tempR1intoR2.max()
tempR1intoR2.min()

tensor(0.2161, device='cuda:0')

9. Find the maximum and minimum index values of the output of 7.

In [20]:
tempR1intoR2.min().argmax()
tempR1intoR2.min().argmin()

tensor(0, device='cuda:0')

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [34]:
randomTensorLast = torch.rand(1, 1, 1, 10)
newRandomTensor1 = torch.squeeze(randomTensor)
# newRandomTensor1.shape

torch.Size([7, 7])